# Generated by Django 3.2.15 on 2022-08-20 21:22

from django.db import migrations, models
import shortener.models
import shortener.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(unique=True)),
                ('url_hash', models.URLField(unique=True)),
                ('clicks', models.IntegerField(default=0)),
                ('expiration_time', models.DateTimeField(default=shortener.models.default_expiration_time, validators=[shortener.validators.validate_datetime])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
