# Generated by Django 3.2.15 on 2022-08-20 19:24

from django.db import migrations, models
import shortener.models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expiration_time',
            field=models.DateTimeField(default=shortener.models.default_expiration_time, validators=[shortener.validators.validate_datetime]),
        ),
    ]
